name: stream_cloudflare
description: "A Flutter plugin to play videos from Cloudflare Stream with Adaptive Quality, Audio Track, and Subtitle Support."
version: 1.0.0
homepage: https://github.com/phatpan/stream_cloudflare
repository: https://github.com/phatpan/stream_cloudflare
issue_tracker: https://github.com/phatpan/stream_cloudflare/issues
documentation: https://github.com/phatpan/stream_cloudflare

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add your dependencies here (e.g., platform channels, ExoPlayer wrapper)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
